services:
  dynamodb-local-hoge:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local-hoge
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  dynamodb-admin-hoge:
    container_name: dynamodb-admin-hoge
    image: aaronshaf/dynamodb-admin:latest
    environment:
      DYNAMO_ENDPOINT: dynamodb-local-hoge:8000
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb-local-hoge